jdk: oraclejdk11
os: osx
osx_image: xcode10.1
language: java
env:
  global:
    - PATH=$HOME/.local/bin:$PATH
    - SYS=25 ABI="google_apis;arm64-v8a"

matrix:
  include:
    - if: commit_message =~ /ios/
      env: TEST_SUITE="TravisTest1"

    - if: commit_message =~ /ios/
      env: TEST_SUITE="TravisTest1"


#android:
#  licenses:
#    - 'android-sdk-preview-license-.+'
#    - 'android-sdk-license-.+'
#    - 'google-gdk-license-.+'
#  components:
#    - tools
#    - tools
#    - platform-tools
#    - extra-google-google_play_services
#    - extra-google-m2repository
#    - extra-android-m2repository
#    - build-tools-28.0.3
#    - android-25
#    - sys-img-arm64-v8a-google_apis-25

install:
  - brew update
  - brew install awscli
  - npm install -g appium@1.9.1
  - brew cask install google-chrome
#  - sudo apt-get update
#  - sudo apt-get install build-essential libssl-dev
#  - sudo curl https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
#  - source ~/.profile
#  - nvm --version
#  - nvm install 10.15.3
#  - nvm use 10.15.3
#  - node -v
#  - npm -v
#  - npm install -g appium@1.9.1




before_script:
#  - android create avd --force -n Pixel_XL_API_25 --abi arm64-v8a -t 1 --tag google_apis
#  - emulator -avd Pixel_XL_API_25 -no-window &
#  - android-wait-for-emulator
  - ./scripts/android-wait-for-emulator.sh
  - adb shell input keyevent 82

  - adb -P 5037 -s emulator-5554 install /home/travis/.nvm/versions/node/v10.15.3/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v1.18.0.apk
  - adb -P 5037 -s emulator-5554 install /home/travis/.nvm/versions/node/v10.15.3/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk

script:
  #  - appium --log-level error &
  - appium &
  - mvn clean verify -Dtags=$TEST_SUITE