jdk: oraclejdk8
sudo: required
dist: trusty
env:
  global:
    - PATH=$HOME/.local/bin:$PATH
    - AWS_DEFAULT_REGION=us-east-1
    - AWS_ACCESS_KEY_ID=AKIATTE2BRS7QYN5VOFY
    - AWS_SECRET_ACCESS_KEY=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

matrix:
  include:
    - if: commit_message =~ /android/
      env: TEST_SUITE="SmokeTestSuit"
      language: generic
      os: linux

    - if: commit_message =~ /android/
      env: TEST_SUITE="TravisTest123"
      language: generic
      os: linux

before_install:
  - ANDROID_TOOLS=4333796 # android-28
  - export ANDROID_HOME=~/android-sdk
  - wget -q "https://dl.google.com/android/repository/sdk-tools-linux-$ANDROID_TOOLS.zip" -O android-sdk-tools.zip
  - unzip -q android-sdk-tools.zip -d ${ANDROID_HOME}
  - rm android-sdk-tools.zip
  - PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/platform-tools
  # Silence warning.
  - mkdir -p ~/.android
  - touch ~/.android/repositories.cfg
  # Accept licenses before installing components, no need to echo y for each component
  - yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses
  # Platform tools
  - $ANDROID_HOME/tools/bin/sdkmanager "emulator" "tools" "platform-tools" > /dev/null
  # install older build tools (for emulator)
  - $ANDROID_HOME/tools/bin/sdkmanager "build-tools;28.0.3" "platforms;android-24" > /dev/null
  - $ANDROID_HOME/tools/bin/sdkmanager "extras;google;m2repository" "extras;google;google_play_services" "extras;android;m2repository" > /dev/null
  # Create and start emulator.
  - $ANDROID_HOME/tools/bin/sdkmanager "system-images;android-24;default;armeabi-v7a" > /dev/null
  - rm -rf $ANDROID_HOME/emulator
  # Install latest canary of emulator
  - cd $ANDROID_HOME
  - sudo apt-get install -y libunwind8 libc++1
  - wget -q "https://dl.google.com/android/repository/emulator-linux-5438295.zip" -O emulator.zip
  - unzip -q emulator.zip
  - cd -
  - echo no | $ANDROID_HOME/tools/bin/avdmanager create avd -n Pixel_XL_API_24 -k "system-images;android-24;default;armeabi-v7a" --device 19
  - $ANDROID_HOME/emulator/mksdcard -l mySdCard 1024M mySdCardFile.img
  - cat /home/travis/.android/avd/Pixel_XL_API_24.avd/config.ini --show-all
  - $ANDROID_HOME/emulator/emulator -avd Pixel_XL_API_24 -no-window -no-audio -memory 1536 -sdcard $ANDROID_HOME/emulator/mySdCardFile.img &
  - $ANDROID_HOME/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'
  - $ANDROID_HOME/platform-tools/adb shell input keyevent 82
  - cat /home/travis/.android/avd/Pixel_XL_API_24.avd/config.ini --show-all

install:
  - |
    if [[ $TRAVIS_OS_NAME == "linux" ]]; then
      sudo apt-get update
      sudo apt-get install build-essential libssl-dev
      sudo curl https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
      source ~/.profile
      nvm install 10.15.3
      nvm use 10.15.3
      npm install -g appium@1.9.1
      sudo apt-get install python3-pip
      pip3 --version
      pip3 install awscli --upgrade --user
      aws --version
    fi

before_script:
  - |
    if [[ $TRAVIS_OS_NAME == "linux" ]]; then
      $ANDROID_HOME/platform-tools/adb -P 5037 -s emulator-5554 install /home/travis/.nvm/versions/node/v10.15.3/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v1.18.0.apk
    fi
  - mkdir -p ~/test_result_report_$TEST_SUITE

script:
  - |
    if [[ $TRAVIS_OS_NAME == "linux" ]]; then
      $ANDROID_HOME/platform-tools/adb -P 5037 -s emulator-5554 install /home/travis/.nvm/versions/node/v10.15.3/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk
    fi

  - |
    if [[ $TRAVIS_OS_NAME == "linux" ]]; then
      appium --log-level error &
      mvn -q clean verify -Dtags=$TEST_SUITE
    fi

  - |
    if [[ $TRAVIS_OS_NAME == "linux" ]]; then
      cd /home/travis/build/antonzenkevich/travisAndroid/target/
      zip -r ${TEST_SUITE}-${TRAVIS_BUILD_NUMBER}.zip site/*
      sudo mv ${TEST_SUITE}-${TRAVIS_BUILD_NUMBER}.zip ~/test_result_report_$TEST_SUITE
      aws s3 cp ~/test_result_report_$TEST_SUITE/${TEST_SUITE}-${TRAVIS_BUILD_NUMBER}.zip s3://travisandroid/tests/ --acl public-read-write
    fi

#sudo: required
#language: java
#
#matrix:
#  include:
#    - if: commit_message =~ /ios/
#      env: TEST_SUITE="TravisTest123"
#      os: osx
#      osx_image: xcode10.2
#      jdk: openjdk12
#
##    - if: commit_message =~ /ios/
##      env: TEST_SUITE="TravisTest1"
##      os: osx
##      osx_image: xcode10.2
##      jdk: openjdk12
#
#install:
#  - |
#    if [[ $TRAVIS_OS_NAME == "osx" ]]; then
#      brew update
#      brew install awscli
#      cd /Users/travis/build/antonzenkevich/travisAndroid
#      unzip "Perchwell Staging.zip"
#      npm install -g appium
#      brew cask install google-chrome
#    fi
#
#script:
#
#  - |
#    if [[ $TRAVIS_OS_NAME == "osx" ]]; then
#      appium &
#      mvn -q clean verify -Dtags=$TEST_SUITE -DtestEnvironment=ios
#    fi