#jdk: oraclejdk8
#os: osx
#osx_image: xcode9.3
#language: java
#env:
#  global:
#    - PATH=$HOME/.local/bin:$PATH
#    - SYS=26 ABI="google_apis;x86"
#
#matrix:
#  include:
#    - if: commit_message =~ /ios/
#      env: TEST_SUITE="TravisTest1"
#
##    - if: commit_message =~ /ios/
##      env: TEST_SUITE="TravisTest1"
#
#before_install:
#  - brew update
#  - mkdir -p ~/.android
#  - touch ~/.android/repositories.cfg
#  # install correct version of java on osx
#  # skip brew update
#  - export HOMEBREW_NO_AUTO_UPDATE=1
#  # Accept licenses before installing components, no need to echo y for each component
#  - brew cask install android-sdk
#  - export ANDROID_SDK_ROOT=/usr/local/share/android-sdk/
#  - export ANDROID_HOME=/usr/local/share/android-sdk/
#  - yes | /usr/local/share/android-sdk/tools/bin/sdkmanager --licenses
#  # Platform tools
#  - brew cask install android-platform-tools
#  - /usr/local/share/android-sdk/tools/bin/sdkmanager "emulator" "tools"
#  # install older build tools (for emulator)
#  - /usr/local/share/android-sdk/tools/bin/sdkmanager "build-tools;28.0.3" "platforms;android-26"
#  # Create and start emulator.
#  - /usr/local/share/android-sdk/tools/bin/sdkmanager "system-images;android-$SYS;$ABI"
#  - echo no | /usr/local/share/android-sdk/tools/bin/avdmanager create avd -n Pixel_XL_API_26 -k "system-images;android-$SYS;$ABI"
#  - /usr/local/share/android-sdk/tools/emulator -avd Pixel_XL_API_26 -no-window -no-skin -no-audio &
#  # fix timezone warning on osx
#  - sudo ln -sf /usr/share/zoneinfo/US/Pacific /etc/localtime
#
#install:
#  - brew install awscli
#  - brew upgrade node
#  - npm install -g appium@1.9.1
#  - brew cask install google-chrome
#
#script:
#  - appium &
#  - mvn -q clean verify -Dtags=$TEST_SUITE

jdk: oraclejdk11
sudo: required
dist: trusty
env:
  global:
    - PATH=$HOME/.local/bin:$PATH
    - SYS=25 ABI="google_apis;x86_64"

matrix:
  include:
    - if: commit_message =~ /android/
      env: TEST_SUITE="TravisTest"
      language: generic
      os: linux

    - if: commit_message =~ /android/
      env: TEST_SUITE="TravisTest1"
      language: generic
      os: linux

#android:
#  licenses:
#    - 'android-sdk-preview-license-.+'
#    - 'android-sdk-license-.+'
#    - 'google-gdk-license-.+'
#  components:
#    - tools
#    - tools
#    - platform-tools
#    - extra-google-google_play_services
#    - extra-google-m2repository
#    - extra-android-m2repository
#    - build-tools-28.0.3
#    - android-25
#    - sys-img-arm64-v8a-google_apis-25

before_install:
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=:99.0
      sh -e /etc/init.d/xvfb start
      sleep 3 # give xvfb some time to start
    fi
# Install android tools
  - ANDROID_TOOLS=4333796 # android-28
  - export ANDROID_HOME=~/android-sdk
  - wget -q "https://dl.google.com/android/repository/sdk-tools-linux-$ANDROID_TOOLS.zip" -O android-sdk-tools.zip
  - unzip -q android-sdk-tools.zip -d ${ANDROID_HOME}
  - rm android-sdk-tools.zip
  - PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/platform-tools
  # Silence warning.
  - mkdir -p ~/.android
  - touch ~/.android/repositories.cfg
  # Accept licenses before installing components, no need to echo y for each component
  - yes | sdkmanager --licenses
  # Platform tools
  - sdkmanager "emulator" "tools" "platform-tools" > /dev/null
  - sdkmanager --list | head -15
  # install older build tools (for emulator)
  - sdkmanager "build-tools;26.0.3" "platforms;android-25" > /dev/null
  # Create and start emulator.
  - sdkmanager "system-images;android-$SYS;$ABI" > /dev/null
  - sdkmanager --list | head -15
  - rm -rf $ANDROID_HOME/emulator
  # Install latest canary of emulator
  - cd $ANDROID_HOME
  - sudo apt-get install -y libunwind8 libc++1
  - wget -q "https://dl.google.com/android/repository/emulator-linux-5438295.zip" -O emulator.zip
  - unzip -q emulator.zip
  - cd -
  - echo no | avdmanager create avd -n Pixel_XL_API_25 -k "system-images;android-$SYS;$ABI"
  - $ANDROID_HOME/emulator/emulator -avd Pixel_XL_API_25 -no-snapshot -no-accel -no-window &
  - adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'
  - adb shell input keyevent 82#

install:
  - |
    if [[ $TRAVIS_OS_NAME == "linux" ]]; then
      sudo apt-get update
      sudo apt-get install build-essential libssl-dev
      sudo curl https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
      source ~/.profile
      nvm --version
      nvm install 10.15.3
      nvm use 10.15.3
      node -v
      npm -v
      npm install -g appium
    fi

before_script:


script:
#  - appium --log-level error &
  - appium &
  - mvn -q clean verify -Dtags=$TEST_SUITE