jdk: oraclejdk11
env:
  global:
    - PATH=$HOME/.local/bin:$PATH

before_install:
  - ANDROID_TOOLS=4333796 # android-28
  - export ANDROID_HOME=~/android-sdk
  - wget -q "https://dl.google.com/android/repository/sdk-tools-darwin-$ANDROID_TOOLS.zip" -O android-sdk-tools.zip
  - unzip -q android-sdk-tools.zip -d ${ANDROID_HOME}
  - rm android-sdk-tools.zip
  - PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/platform-tools
  - mkdir -p ~/.android
  - touch ~/.android/repositories.cfg
  - export HOMEBREW_NO_AUTO_UPDATE=1
  - brew cask uninstall java; brew tap caskroom/versions; brew cask install java8
  - yes | sdkmanager --licenses
  - sdkmanager "emulator" "tools" "platform-tools" > /dev/null
  - sdkmanager --list | head -15
  - sdkmanager "build-tools;25.0.2" "platforms;android-25" > /dev/null
  - sdkmanager "system-images;android-25;google_apis;armeabi-v7a > /dev/null
  - sdkmanager --list | head -15
  - echo no | avdmanager create avd -n test -k "system-images;android-25;google_apis;armeabi-v7a"
  - sudo ln -sf /usr/share/zoneinfo/US/Pacific /etc/localtime
    EMU_PARAMS="-no-window -gpu swiftshader"
  - emulator -avd test -no-audio $EMU_PARAMS $EMU_ADDITIONAL_OPTIONS ${EMU_DEBUG} &

before_script:
  - android-wait-for-emulator
  - adb shell input keyevent 82

script:
  - echo "Done."