jdk: oraclejdk8
os: osx
osx_image: xcode9.3
language: java
env:
  global:
    - PATH=$HOME/.local/bin:$PATH
    - SYS=26 ABI="google_apis;x86"

matrix:
  include:
    - if: commit_message =~ /ios/
      env: TEST_SUITE="TravisTest1"

#    - if: commit_message =~ /ios/
#      env: TEST_SUITE="TravisTest1"

before_install:
  # Install android tools
  - ANDROID_TOOLS=4333796 # android-28
  - export ANDROID_HOME=~/android-sdk
  - wget -q "https://dl.google.com/android/repository/sdk-tools-darwin-$ANDROID_TOOLS.zip" -O android-sdk-tools.zip
  - unzip -q android-sdk-tools.zip -d ${ANDROID_HOME}
  - rm android-sdk-tools.zip
  - PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/platform-tools
  # Silence warning.
  - mkdir -p ~/.android
  - touch ~/.android/repositories.cfg
  # install correct version of java on osx
  # skip brew update
  - export HOMEBREW_NO_AUTO_UPDATE=1
  # Accept licenses before installing components, no need to echo y for each component
  - brew cask install android-sdk
  - export ANDROID_SDK_ROOT="/usr/local/share/android-sdk"
  - yes | /usr/local/bin/sdkmanager --licenses
  # Platform tools
  - sdkmanager "emulator" "tools" "platform-tools"
  - sdkmanager --list | head -15
  # install older build tools (for emulator)
  - sdkmanager "build-tools;28.0.3" "platforms;android-26"
  # Create and start emulator.
  - sdkmanager "system-images;android-$SYS;$ABI"
  - sdkmanager --list | head -15
  - echo no | avdmanager create avd -n Pixel_XL_API_26 -k "system-images;android-$SYS;$ABI"
  # fix timezone warning on osx
  - sudo ln -sf /usr/share/zoneinfo/US/Pacific /etc/localtime

install:
  - brew update
  - brew install awscli
  - brew upgrade node
  - npm install -g appium@1.9.1
  - brew cask install google-chrome

before_script:
  - emulator -avd Pixel_XL_API_26 -no-window &
#  - android-wait-for-emulator
#  - adb shell input keyevent 82

#  - adb -P 5037 -s emulator-5554 install /home/travis/.nvm/versions/node/v10.15.3/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v1.18.0.apk
#  - adb -P 5037 -s emulator-5554 install /home/travis/.nvm/versions/node/v10.15.3/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk

script:
  - appium &
  - mvn clean verify -Dtags=$TEST_SUITE